swagger: "2.0"
info:
  version: "0.0.1"
  title: We're Nerds Dude!!
# during dev, should point to your local machine
host: localhost:10000
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:

  /routines/:
    # binds a127 app logic to a route
    x-swagger-router-controller: routines
    get:
      description: Post request for user to log-in
      # used as the method name of the controller
      operationId: routines
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/RoutinesResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /routines/{id}:
    # binds a127 app logic to a route
    x-swagger-router-controller: routines
    get:
      description: Post request for user to log-in
      # used as the method name of the controller
      operationId: routinesId
      parameters:
        - name: id
          in: path
          required: true
          type: string
          
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/RoutinesResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /routines/{id}/exercises:
    # binds a127 app logic to a route
    x-swagger-router-controller: routines-exercises
    get:
      description: Get request returns exercises for specific routine
      # used as the method name of the controller
      operationId: routinesIdExercises
      parameters:
        - name: id
          in: path
          required: true
          type: string
          
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/RoutinesResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /exercises:
    # binds a127 app logic to a route
    x-swagger-router-controller: exercises
    get:
      description: Post request for user to log-in
      # used as the method name of the controller
      operationId: exercises
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/RoutinesResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /exercises/{id}:
    # binds a127 app logic to a route
    x-swagger-router-controller: exercises
    get:
      description: Post request for user to log-in
      # used as the method name of the controller
      operationId: exercisesId
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/RoutinesResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    
  /users/signup:
    # binds a127 app logic to a route
    x-swagger-router-controller: users

    post:
      description: Returns predefined routines to the user
      # used as the method name of the controller
      operationId: users
      parameters:
        - name: first_name
          description: Input first name
          in: query
          required: true
          type: string
          
        - name: last_name
          description: Input last name
          in: query
          required: true
          type: string
        
        - name: weight
          description: Input user weight
          in: query
          required: true
          type: integer
          
        - name: email
          description: Input email
          in: query
          required: true
          type: string
          
        - name: password
          description: Input password
          in: query
          required: true
          type: string
          
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/RoutinesResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /users/:
    # binds a127 app logic to a route
    x-swagger-router-controller: users
    post:
      description: Post request for user to log-in
      # used as the method name of the controller
      operationId: usersId
      parameters:
        - name: email
          in: query
          required: true
          type: string
          
        - name: password
          in: query
          required: true
          type: string
          
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/RoutinesResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /users/{user_id}/routines:
    # binds a127 app logic to a route
    x-swagger-router-controller: users_id_routines
    post:
      description: Post request for user to create routine
      # used as the method name of the controller
      operationId: user_id_routines
      parameters:
        - name: user_id
          in: path
          required: true
          type: integer
        - name: name
          in: query
          required: true
          type: string
        
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/RoutinesResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"







  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  RoutinesResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
        

