swagger: "2.0"
info:
  version: "0.0.1"
  title: We're Nerds Dude!!
# during dev, should point to your local machine
host: localhost:10000
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:

  /routines:
    # binds a127 app logic to a route
    x-swagger-router-controller: routines

    get:
      description: Returns predefined routines to the user
      # used as the method name of the controller
      operationId: routines
      parameters:
        - name: integer
          description: Input an integer (optional)
          in: query
          required: false
          type: string
          
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/RoutinesResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
            
            
  /routines/{id}:
    # binds a127 app logic to a route
    x-swagger-router-controller: routinesId
    get:
      description: Returns predefined routines to the user
      # used as the method name of the controller
      operationId: routinesId
      parameters:
        - name: Integer
          in: query
          required: false
          type: string
          
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/RoutinesResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"



  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  RoutinesResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
        

